spring:
  profiles:
    active: local
  application:
    name: CUSTOM-ANNOTION
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
---
server:
  port: 7777
########################################
#   Druid数据库配置
########################################
spring:
  profiles: local
  redis:
    host: localhost
redisson:
  cluster: false
  address: redis://localhost:6379
  password:
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  scanInterval: 5000
  loadBalancer: org.redisson.connection.balancer.RoundRobinLoadBalancer
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: SLAVE
  subscriptionMode: MASTER

########################################
#   日志配置
########################################
logging:
  level:
    com.iweixiao.erudite.repository: debug

---
server:
  port: 80
########################################
#   Druid数据库配置
########################################
spring:
  profiles: dev
  redis:
    host: localhost
redisson:
  cluster: false
  address: redis://localhost:6379
  password:
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  scanInterval: 5000
  loadBalancer: org.redisson.connection.balancer.RoundRobinLoadBalancer
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: SLAVE
  subscriptionMode: MASTER

########################################
#   日志配置
########################################
logging:
  level:
    root: info

---
server:
  port: 80
########################################
#   Druid数据库配置
########################################
spring:
  profiles: test
  redis:
    host: localhost
redisson:
  cluster: false
  address: redis://localhost:6379
  password:
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  scanInterval: 5000
  loadBalancer: org.redisson.connection.balancer.RoundRobinLoadBalancer
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: SLAVE
  subscriptionMode: MASTER

########################################
#   日志配置
########################################
logging:
  level:
    root: info